title: "Decoding the Magic of Compilers"
description: "A comprehensive exploration of compiler optimization techniques"
baseurl: "/decoding-magic-of-compiler"
url: "https://mohitmishra786.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collection settings
collections:
  chapters:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: "chapters"
    values:
      layout: "chapter"
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/
  - .github/
  - .gitignore 